#!/usr/bin/env python3
"""
build-reference.py — Extract authoritative contract catalogs from the pinned Mattermost
source clone, so the implementing agent searches facts instead of guessing them.

Generates, under reference/:
  config-env-map.md   — every MM_* env var (from server/public/model/config.go)
  plugin-api.md       — the plugin API surface (from server/public/plugin/api.go)
  mmctl-commands.md   — the mmctl CLI command catalog
  endpoints.md        — REST API endpoint catalog (from api/v4/source/*.yaml)

Usage:  python3 scripts/build-reference.py [SRC_DIR] [OUT_DIR]
  SRC_DIR default: ~/mattermost-src/mattermost   OUT_DIR default: ./reference
"""
import os, re, sys, glob

SRC = os.path.expanduser(sys.argv[1] if len(sys.argv) > 1 else "~/mattermost-src/mattermost")
OUT = sys.argv[2] if len(sys.argv) > 2 else os.path.join(os.path.dirname(__file__), "..", "reference")
OUT = os.path.abspath(OUT)
os.makedirs(OUT, exist_ok=True)

def banner(f, title, src):
    f.write(f"# {title}\n\n")
    f.write("> AUTO-GENERATED by `scripts/build-reference.py` — do not edit by hand.\n")
    f.write(f"> Source of truth: `{src}`\n")
    f.write("> Regenerate after pinning the source to your `MM_VERSION`.\n\n")

# ---------- 1. config -> env var map ----------
def build_config():
    path = os.path.join(SRC, "server/public/model/config.go")
    text = open(path, encoding="utf-8", errors="replace").read()
    # capture every `type X struct { ... }`
    structs = {}
    for m in re.finditer(r"^type (\w+) struct \{\n(.*?)^\}", text, re.S | re.M):
        name, body = m.group(1), m.group(2)
        fields = []
        for line in body.splitlines():
            fm = re.match(r"\s+([A-Z]\w*)\s+(\*?[\w\.\[\]]+)(?:\s+`([^`]*)`)?", line)
            if fm:
                fname, ftype, tag = fm.group(1), fm.group(2), fm.group(3) or ""
                jm = re.search(r'json:"([^",]+)', tag)
                fields.append((fname, ftype, jm.group(1) if jm else ""))
        structs[name] = fields
    if "Config" not in structs:
        return 0
    out = open(os.path.join(OUT, "config-env-map.md"), "w", encoding="utf-8")
    banner(out, "Config → MM_* Environment Variable Map", "server/public/model/config.go")
    out.write("Mattermost maps `Config.<Section>.<Field>` to env var `MM_<SECTION>_<FIELD>` (uppercased).\n")
    out.write("Use these EXACT names in `.env`/compose. Deeper nested structs add further `_<FIELD>` levels.\n\n")
    count = 0
    for sect, stype, _ in structs["Config"]:
        base = stype.lstrip("*")
        if base not in structs:
            continue
        out.write(f"## MM_{sect.upper()}  (`{base}`)\n\n")
        out.write("| Env var | Go type | json key |\n|---|---|---|\n")
        for fname, ftype, jkey in structs[base]:
            out.write(f"| `MM_{sect.upper()}_{fname.upper()}` | {ftype} | {jkey} |\n")
            count += 1
        out.write("\n")
    out.close()
    return count

# ---------- 2. plugin API ----------
def build_plugin():
    path = os.path.join(SRC, "server/public/plugin/api.go")
    if not os.path.exists(path):
        return 0
    text = open(path, encoding="utf-8", errors="replace").read()
    out = open(os.path.join(OUT, "plugin-api.md"), "w", encoding="utf-8")
    banner(out, "Plugin API Surface", "server/public/plugin/api.go")
    out.write("Methods available to a server plugin via `plugin.API`. Used by GOAL-06 (AI translation).\n\n")
    count = 0
    cur_doc = []
    for line in text.splitlines():
        dm = re.match(r"\s*//\s?(.*)", line)
        mm = re.match(r"\s+([A-Z]\w+)\((.*?)\)(.*)", line)
        if dm and mm is None:
            cur_doc.append(dm.group(1))
        elif mm:
            sig = f"{mm.group(1)}({mm.group(2)}){mm.group(3)}".strip()
            doc = " ".join(cur_doc)[:160]
            out.write(f"- `{sig}`" + (f"  \n  _{doc}_" if doc else "") + "\n")
            count += 1
            cur_doc = []
        else:
            cur_doc = []
    out.close()
    return count

# ---------- 3. mmctl commands ----------
def build_mmctl():
    files = glob.glob(os.path.join(SRC, "server/cmd/mmctl/commands/*.go"))
    out = open(os.path.join(OUT, "mmctl-commands.md"), "w", encoding="utf-8")
    banner(out, "mmctl Command Catalog", "server/cmd/mmctl/commands/*.go")
    out.write("Cobra commands (`Use` / `Short`). Used by all provisioning/branding/plugin scripts.\n\n")
    out.write("| Use | Short |\n|---|---|\n")
    count = 0
    for fp in sorted(files):
        t = open(fp, encoding="utf-8", errors="replace").read()
        uses = re.findall(r'Use:\s*"([^"]+)"', t)
        shorts = re.findall(r'Short:\s*"([^"]+)"', t)
        for i, u in enumerate(uses):
            s = shorts[i] if i < len(shorts) else ""
            out.write(f"| `{u}` | {s} |\n")
            count += 1
    out.close()
    return count

# ---------- 4. REST endpoints ----------
def build_endpoints():
    files = glob.glob(os.path.join(SRC, "api/v4/source/*.yaml"))
    out = open(os.path.join(OUT, "endpoints.md"), "w", encoding="utf-8")
    banner(out, "REST API v4 Endpoint Catalog", "api/v4/source/*.yaml (OpenAPI)")
    out.write("Endpoint summary. Full request/response schema: see the source YAML or the Redoc render.\n\n")
    out.write("| Method | Path | operationId | Summary |\n|---|---|---|---|\n")
    count = 0
    path_re = re.compile(r"^  (/api/v4/\S+):\s*$")
    meth_re = re.compile(r"^    (get|post|put|delete|patch):\s*$")
    for fp in sorted(files):
        lines = open(fp, encoding="utf-8", errors="replace").read().splitlines()
        cur_path = None
        for i, line in enumerate(lines):
            pm = path_re.match(line)
            if pm:
                cur_path = pm.group(1); continue
            mm = meth_re.match(line)
            if mm and cur_path:
                method = mm.group(1).upper()
                blk = "\n".join(lines[i:i+25])
                summ = re.search(r"summary:\s*(.+)", blk)
                opid = re.search(r"operationId:\s*(\w+)", blk)
                out.write(f"| {method} | `{cur_path}` | {opid.group(1) if opid else ''} | {(summ.group(1).strip() if summ else '')[:80]} |\n")
                count += 1
    out.close()
    return count

print("config env vars :", build_config())
print("plugin methods  :", build_plugin())
print("mmctl commands  :", build_mmctl())
print("rest endpoints  :", build_endpoints())
print("written to      :", OUT)
